ARG KEYCLOAK_VERSION=26.3

# Build with any custom providers
FROM quay.io/keycloak/keycloak:${KEYCLOAK_VERSION} AS builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure a database vendor
ENV KC_DB=postgres

WORKDIR /opt/keycloak

ARG DYNAMIC_AGE_MAPPER_SPI_VERSION=1.0.0

ADD --chown=keycloak:keycloak --chmod=644 \
    https://github.com/agora-net/keycloak-spis/releases/download/v${DYNAMIC_AGE_MAPPER_SPI_VERSION}/dynamic-scope-spi-${DYNAMIC_AGE_MAPPER_SPI_VERSION}.jar \
    /opt/keycloak/providers/

RUN /opt/keycloak/bin/kc.sh build

# Copy built assets into the runtime image
FROM quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
