# Generated by Django 5.2.6 on 2025-10-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agorauser",
            name="handle",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=32,
                null=True,
                unique=True,
                verbose_name="Handle of User",
            ),
        ),
    ]
