# Generated by Django 5.2.6 on 2025-09-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agorauser",
            name="handle",
            field=models.CharField(blank=True, max_length=32, verbose_name="Handle of User"),
        ),
    ]
