# Generated by Django 5.2.6 on 2025-10-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_agorauser_handle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identityverification",
            name="identity_verification_status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("verified", "Verified"),
                    ("requires_action", "Requires Action"),
                    ("failed", "Failed"),
                ],
                max_length=15,
            ),
        ),
    ]
