# Generated by Django 5.2.6 on 2025-10-08 19:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_identityverification_identity_verification_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="identityverification",
            old_name="identity_verification_external_id",
            new_name="external_id",
        ),
        migrations.RenameField(
            model_name="identityverification",
            old_name="identity_verification_service",
            new_name="service",
        ),
        migrations.RenameField(
            model_name="identityverification",
            old_name="identity_verification_status",
            new_name="status",
        ),
    ]
