# Generated by Django 5.2.6 on 2025-10-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0004_rename_identity_verification_external_id_identityverification_external_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_service",
                    models.CharField(choices=[("stripe", "Stripe")], max_length=10),
                ),
                ("payment_session_id", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("amount_cents", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
