# Generated by Django 5.2.6 on 2025-10-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_donation"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="currency",
            field=models.CharField(
                choices=[("chf", "Chf"), ("usd", "Usd")], default="chf", max_length=10
            ),
        ),
    ]
