# Generated by Django 5.2.6 on 2025-10-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_donation_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="invite_code",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
