# Generated by Django 5.2.6 on 2025-10-28 14:31

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="theme_color",
            field=colorfield.fields.ColorField(
                blank=True, default=None, image_field=None, max_length=25, null=True, samples=None
            ),
        ),
    ]
