# Generated by Django 5.2.6 on 2025-11-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_userprofile_theme_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name="Bio"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="company",
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Company"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="interests",
            field=models.JSONField(blank=True, default=list, verbose_name="Interests"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="job_title",
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Job Title"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_links",
            field=models.JSONField(blank=True, default=list, verbose_name="Profile Links"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pronouns",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Pronouns"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="relationship_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("in_a_relationship", "In a relationship"),
                    ("married", "Married"),
                    ("divorced", "Divorced"),
                    ("widowed", "Widowed"),
                    ("its_complicated", "It's complicated"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                max_length=20,
                null=True,
                verbose_name="Relationship Status",
            ),
        ),
    ]
