# Generated by Django 5.2.6 on 2025-11-08 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_userprofile_bio_userprofile_company_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_links",
        ),
        migrations.CreateModel(
            name="UserProfileLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField()),
                ("label", models.CharField(blank=True, max_length=100, verbose_name="Label")),
                (
                    "position",
                    models.PositiveIntegerField(db_index=True, default=1, verbose_name="Position"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile Link",
                "verbose_name_plural": "User Profile Links",
                "ordering": ["position", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "position"), name="uniq_profile_link_position"
                    )
                ],
            },
        ),
    ]
