# Generated by Django 5.2.6 on 2025-11-08 18:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_remove_userprofile_profile_links_userprofilelink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofilelink",
            name="label",
        ),
    ]
