# Generated by Django 5.2.6 on 2025-11-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_remove_userprofilelink_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this profile will be visible to everyone, including unauthenticated users.",
                verbose_name="Is Public",
            ),
        ),
    ]
